version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn && yarn build
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /tmp/artifacts
            tar -zcvf /tmp/artifacts/build-$(date "+%d%m%y-%H%M%S").tar.gz public;
      - store_artifacts:
          path: mkdir /tmp/artifacts
